### ISSUE TITLE
isolate_manager:generate does not suppress intermediate files

### ISSUE THREAD

**Issue by andynewman10** [lamnhan066/isolate_manager#36]
Temporary `lib/.IsolateManagerWorker.*` files are no longer getting cleaned out once the generation process is finished for me. I remember this was working before. I started to get this behavior when passing flags directly to the Dart to Js compiler on the command line.

Using Flutter 3.24.3 on Windows 11.

Tested on isolate_manager 5.4.0 and 5.5.0.

**Comment by lamnhan066** [comment]
Hi @andynewman10 

Could you show me the full command you're using?

**Comment by lamnhan066** [comment]
Hi @andynewman10 

What version of the `isolate_manager_generator` are you using? The old version will fail to remove the temporary files if we pass the Dart native flags, but it should be fixed.

**Comment by andynewman10** [comment]
When using isolate_manager 5.4.0, there is no dependency on isolate_manager_generator in my pubspec.lock file.

When using isolate_manager 5.7.4, there is a dependency on isolate_manager_generator 0.0.11 that shows up in my pubspec.lock file. And I do confirm the temporary files are not deleted in this configuration.

**Comment by andynewman10** [comment]
And I confirm the bug still persists with version 6.0.0-rc.23.

**Comment by lamnhan066** [comment]
A possible issue is that Dart doesn't have permission to remove files, possibly because the project is located within the C drive. If this is the thing happened, the package should print the message.

**Comment by andynewman10** [comment]
I agree this problem is weird, however you are generating `.IsolateManagerWorker.*.dart` files just next to the source code files, and because of this, there is no reason why they could not be deleted. All of my source files are within my home directory hierarchy.

**Comment by lamnhan066** [comment]
Could you please send me the commands you have used so I can test them on my side?

**Comment by andynewman10** [comment]
I wonder if temporary files cannot be deleted because they are somehow accessed by VS code. Since you are generating files with the .dart extension, it is possible that VS code somehow tries to read these files and prevent them from being deleted.

Could you tell me where to change the extension in the source code? I could test and tell you if things improve.

**Comment by andynewman10** [comment]
The problem seems intermittent, almost unpredictable, which could suggest it is because of a some random component (VS Code? VS Code Dart extension?) is tyring to read the intermediate file.

**Comment by lamnhan066** [comment]
You can change it here:

https://github.com/lamnhan066/isolate_manager_generator/blob/e7bda9f34b7133f4d390764b8ba219939873d444/lib/src/generate_single.dart#L201

**Comment by andynewman10** [comment]
Thank you, I am going to give it a go.

Another solution would be to generate the files outside of the source tree (like a in a temp directory)

**Comment by lamnhan066** [comment]
I considered this when implementing the feature, but managing the import requires more effort, so I decided to do it later.

**Comment by andynewman10** [comment]
I tried changing the extension to .dart.tmp, to no avail. The intermediate files are still there.

**Comment by andynewman10** [comment]
Ouch, I understand now: I am using the `--debug` flag, which tells the generator not to delete intermediate files! Somehow, files were deleted a long time ago, but this is no longer the case.
